baseURL = "https://ptrk.io/"
languageCode = 'en-us'
title = "Patrik Cyvoct"
theme = 'hello-friend-ng'

# enableGitInfo = true
enableEmoji = true


[permalinks]
posts = "/posts/:year/:month/:title/"

[params]
# gitUrl = "https://github.com/Sh4d1/blog/commit/"

dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"

homeSubtitle = "French Cloud enthusiast. Kubernetes, Rust, Go & C."

disableReadOtherPosts = false

enableSharingButtons = true

enableThemeToggle = true

description = "French Cloud enthusiast. Kubernetes, Rust, Go & C."
keywords = "kubernetes, blog, rust, containers, go, c"
images = [""]
[params.author]
name = "Patrik Cyvoct"

[params.footer]
rss = true

PygmentsCodeFences = true
PygmentStyle = "nord"
topText = []
bottomText = [
  "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
  "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>",
]


[params.logo]
logoMark = ">"
logoText = "cd /home/patrik"
logoHomeLink = "/"

[params.portrait]
path = "/images/su_doku.jpg"
alt = "Binary Sudoku"
maxWidth = "200px"

[[params.social]]
name = "email"
url = "mailto:patrik@ptrk.io"
[[params.social]]
name = "github"
url = "https://github.com/Sh4d1"
[[params.social]]
name = "twitter"
url = "https://twitter.com/PatrikCyvoct"
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/patrik-cyvoct/"

[taxonomies]
category = "blog"
tag = "tags"
series = "series"


[languages]
[languages.en]
title = "Patrik Cyvoct"

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "https://resume.ptrk.io"
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "posts/"
